// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Province = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_Province,
                            "河北省\n山西省\n辽宁省\n吉林省\n黑龙江省\n江苏省\n浙江省\n安徽省\n福建省\n江西省\n山东省\n河南省\n湖北省\n湖南省\n广东省\n海南省\n四川省\n贵州省\n云南省\n陕西省\n甘肃省\n青海省\n台湾省\n内蒙古自治区\n广西壮族自治区\n西藏自治区\n宁夏回族自治区\n新疆维吾尔自治区\n其他");
    lv_obj_set_width(ui_Province, 150);
    lv_obj_set_height(ui_Province, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Province, -200);
    lv_obj_set_y(ui_Province, -200);
    lv_obj_set_align(ui_Province, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Province, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Province, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Province, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Province), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City,
                            "石家庄市\n唐山市\n秦皇岛市\n邯郸市\n邢台市\n保定市\n张家口市\n承德市\n沧州市\n廊坊市\n衡水市");
    lv_obj_set_width(ui_City, 150);
    lv_obj_set_height(ui_City, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City, -50);
    lv_obj_set_y(ui_City, -200);
    lv_obj_set_align(ui_City, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City1 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City1,
                            "太原市\n大同市\n阳泉市\n长治市\n晋城市\n朔州市\n晋中市\n运城市\n忻州市\n临汾市\n吕梁市\n");
    lv_obj_set_width(ui_City1, 150);
    lv_obj_set_height(ui_City1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City1, -50);
    lv_obj_set_y(ui_City1, -200);
    lv_obj_set_align(ui_City1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City1, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City1), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City2 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City2,
                            "沈阳市\n大连市\n鞍山市\n抚顺市\n本溪市\n丹东市\n锦州市\n营口市\n阜新市\n辽阳市\n盘锦市\n铁岭市\n朝阳市\n葫芦岛市");
    lv_obj_set_width(ui_City2, 150);
    lv_obj_set_height(ui_City2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City2, -50);
    lv_obj_set_y(ui_City2, -200);
    lv_obj_set_align(ui_City2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City2, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City2, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City2), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City3 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City3,
                            "长春市\n吉林市\n四平市\n辽源市\n通化市\n白山市\n松原市\n白城市\n延边朝鲜族自治州");
    lv_obj_set_width(ui_City3, 150);
    lv_obj_set_height(ui_City3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City3, -50);
    lv_obj_set_y(ui_City3, -200);
    lv_obj_set_align(ui_City3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City3, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City3, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City3), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City4 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City4,
                            "哈尔滨市\n齐齐哈尔市\n鸡西市\n鹤岗市\n双鸭山市\n大庆市\n伊春市\n佳木斯市\n七台河市\n牡丹江市\n黑河市\n绥化市\n大兴安岭地区");
    lv_obj_set_width(ui_City4, 150);
    lv_obj_set_height(ui_City4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City4, -50);
    lv_obj_set_y(ui_City4, -200);
    lv_obj_set_align(ui_City4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City4, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City4, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City4), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City5 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City5,
                            "南京市\n无锡市\n徐州市\n常州市\n苏州市\n南通市\n连云港市\n淮安市\n盐城市\n扬州市\n镇江市\n泰州市\n宿迁市");
    lv_obj_set_width(ui_City5, 150);
    lv_obj_set_height(ui_City5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City5, -50);
    lv_obj_set_y(ui_City5, -200);
    lv_obj_set_align(ui_City5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City5, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City5, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City5), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City6 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City6,
                            "杭州市\n宁波市\n温州市\n嘉兴市\n湖州市\n绍兴市\n金华市\n衢州市\n舟山市\n台州市\n丽水市");
    lv_obj_set_width(ui_City6, 150);
    lv_obj_set_height(ui_City6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City6, -50);
    lv_obj_set_y(ui_City6, -200);
    lv_obj_set_align(ui_City6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City6, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City6, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City6), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City7 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City7,
                            "合肥市\n芜湖市\n蚌埠市\n淮南市\n马鞍山市\n淮北市\n铜陵市\n安庆市\n黄山市\n滁州市\n阜阳市\n宿州市\n六安市\n亳州市\n池州市\n宣城市");
    lv_obj_set_width(ui_City7, 150);
    lv_obj_set_height(ui_City7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City7, -50);
    lv_obj_set_y(ui_City7, -200);
    lv_obj_set_align(ui_City7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City7, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City7, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City7), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City8 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City8,
                            "福州市\n厦门市\n莆田市\n三明市\n泉州市\n漳州市\n南平市\n龙岩市\n宁德市");
    lv_obj_set_width(ui_City8, 150);
    lv_obj_set_height(ui_City8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City8, -50);
    lv_obj_set_y(ui_City8, -200);
    lv_obj_set_align(ui_City8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City8, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City8, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City8), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City9 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City9,
                            "南昌市\n景德镇市\n萍乡市\n九江市\n新余市\n鹰潭市\n赣州市\n吉安市\n宜春市\n抚州市\n上饶市");
    lv_obj_set_width(ui_City9, 150);
    lv_obj_set_height(ui_City9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City9, -50);
    lv_obj_set_y(ui_City9, -200);
    lv_obj_set_align(ui_City9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City9, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City9, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City9), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City10 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City10,
                            "济南市\n青岛市\n淄博市\n枣庄市\n东营市\n烟台市\n潍坊市\n济宁市\n泰安市\n威海市\n日照市\n临沂市\n德州市\n聊城市\n滨州市\n菏泽市");
    lv_obj_set_width(ui_City10, 150);
    lv_obj_set_height(ui_City10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City10, -50);
    lv_obj_set_y(ui_City10, -200);
    lv_obj_set_align(ui_City10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City10, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City10, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City10), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City11 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City11,
                            "郑州市\n开封市\n洛阳市\n平顶山市\n安阳市\n鹤壁市\n新乡市\n焦作市\n濮阳市\n许昌市\n漯河市\n三门峡市\n南阳市\n商丘市\n信阳市\n周口市\n驻马店市\n济源市");
    lv_obj_set_width(ui_City11, 150);
    lv_obj_set_height(ui_City11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City11, -50);
    lv_obj_set_y(ui_City11, -200);
    lv_obj_set_align(ui_City11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City11, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City11, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City11), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City12 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City12,
                            "武汉市\n黄石市\n十堰市\n宜昌市\n襄阳市\n鄂州市\n荆门市\n孝感市\n荆州市\n黄冈市\n咸宁市\n随州市\n恩施土家族苗族自治州\n仙桃市\n潜江市\n天门市\n神农架林区");
    lv_obj_set_width(ui_City12, 150);
    lv_obj_set_height(ui_City12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City12, -50);
    lv_obj_set_y(ui_City12, -200);
    lv_obj_set_align(ui_City12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City12, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City12, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City12), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City13 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City13,
                            "长沙市\n株洲市\n湘潭市\n衡阳市\n邵阳市\n岳阳市\n常德市\n张家界市\n益阳市\n郴州市\n永州市\n怀化市\n娄底市\n湘西土家族苗族自治州");
    lv_obj_set_width(ui_City13, 150);
    lv_obj_set_height(ui_City13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City13, -50);
    lv_obj_set_y(ui_City13, -200);
    lv_obj_set_align(ui_City13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City13, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City13, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City13), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City14 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City14,
                            "广州市\n韶关市\n深圳市\n珠海市\n汕头市\n佛山市\n江门市\n湛江市\n茂名市\n肇庆市\n惠州市\n梅州市\n汕尾市\n河源市\n阳江市\n清远市\n东莞市\n中山市\n潮州市\n揭阳市\n云浮市");
    lv_obj_set_width(ui_City14, 150);
    lv_obj_set_height(ui_City14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City14, -50);
    lv_obj_set_y(ui_City14, -200);
    lv_obj_set_align(ui_City14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City14, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City14, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City14), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City15 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City15,
                            "海口市\n三亚市\n三沙市\n儋州市\n五指山市\n文昌市\n琼海市\n万宁市\n东方市");
    lv_obj_set_width(ui_City15, 150);
    lv_obj_set_height(ui_City15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City15, -50);
    lv_obj_set_y(ui_City15, -200);
    lv_obj_set_align(ui_City15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City15, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City15, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City15), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City16 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City16,
                            "成都市\n自贡市\n攀枝花市\n泸州市\n德阳市\n绵阳市\n广元市\n遂宁市\n内江市\n乐山市\n南充市\n宜宾市\n广安市\n达州市\n雅安市\n巴中市\n资阳市\n眉山市\n阿坝藏族羌族自治州\n甘孜藏族自治州\n凉山彝族自治州");
    lv_obj_set_width(ui_City16, 150);
    lv_obj_set_height(ui_City16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City16, -50);
    lv_obj_set_y(ui_City16, -200);
    lv_obj_set_align(ui_City16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City16, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City16, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City16), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City17 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City17,
                            "贵阳市\n六盘水市\n遵义市\n安顺市\n毕节市\n铜仁市\n黔西南布依族苗族自治州\n黔东南苗族侗族自治州\n黔南布依族苗族自治州");
    lv_obj_set_width(ui_City17, 150);
    lv_obj_set_height(ui_City17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City17, -50);
    lv_obj_set_y(ui_City17, -200);
    lv_obj_set_align(ui_City17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City17, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City17, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City17), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City18 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City18,
                            "昆明市\n曲靖市\n玉溪市\n保山市\n昭通市\n丽江市\n普洱市\n临沧市\n楚雄彝族自治州\n红河哈尼族彝族自治州\n文山壮族苗族自治州\n西双版纳傣族自治州\n大理白族自治州\n德宏傣族景颇族自治州\n怒江傈僳族自治州\n迪庆藏族自治州");
    lv_obj_set_width(ui_City18, 150);
    lv_obj_set_height(ui_City18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City18, -50);
    lv_obj_set_y(ui_City18, -200);
    lv_obj_set_align(ui_City18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City18, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City18, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City18), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City19 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City19,
                            "西安市\n铜川市\n宝鸡市\n咸阳市\n渭南市\n延安市\n汉中市\n榆林市\n安康市\n商洛市");
    lv_obj_set_width(ui_City19, 150);
    lv_obj_set_height(ui_City19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City19, -50);
    lv_obj_set_y(ui_City19, -200);
    lv_obj_set_align(ui_City19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City19, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City19, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City19), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City20 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City20,
                            "兰州市\n嘉峪关市\n金昌市\n白银市\n天水市\n武威市\n张掖市\n平凉市\n酒泉市\n庆阳市\n定西市\n陇南市\n临夏回族自治州\n甘南藏族自治州");
    lv_obj_set_width(ui_City20, 150);
    lv_obj_set_height(ui_City20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City20, -50);
    lv_obj_set_y(ui_City20, -200);
    lv_obj_set_align(ui_City20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City20, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City20, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City20), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City21 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City21,
                            "西宁市\n海东市\n海北藏族自治州\n黄南藏族自治州\n海南藏族自治州\n果洛藏族自治州\n玉树藏族自治州\n海西蒙古族藏族自治州");
    lv_obj_set_width(ui_City21, 150);
    lv_obj_set_height(ui_City21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City21, -50);
    lv_obj_set_y(ui_City21, -200);
    lv_obj_set_align(ui_City21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City21, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City21, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City21), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City22 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City22,
                            "台北市\n新北市\n桃园市\n台中市\n台南市\n高雄市\n基隆市\n新竹市\n嘉义市");
    lv_obj_set_width(ui_City22, 150);
    lv_obj_set_height(ui_City22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City22, -50);
    lv_obj_set_y(ui_City22, -200);
    lv_obj_set_align(ui_City22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City22, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City22, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City22), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City28 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City28, "北京市\n上海市\n天津市\n重庆市\n香港\n澳门");
    lv_obj_set_width(ui_City28, 150);
    lv_obj_set_height(ui_City28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City28, -50);
    lv_obj_set_y(ui_City28, -200);
    lv_obj_set_align(ui_City28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City28, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City28, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City28), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City23 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City23,
                            "呼和浩特市\n包头市\n乌海市\n赤峰市\n通辽市\n鄂尔多斯市\n呼伦贝尔市\n巴彦淖尔市\n乌兰察布市");
    lv_obj_set_width(ui_City23, 150);
    lv_obj_set_height(ui_City23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City23, -50);
    lv_obj_set_y(ui_City23, -200);
    lv_obj_set_align(ui_City23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City23, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City23, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City23), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City24 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City24,
                            "南宁市\n柳州市\n桂林市\n梧州市\n北海市\n防城港市\n钦州市\n贵港市\n玉林市\n百色市\n贺州市\n河池市\n来宾市\n崇左市");
    lv_obj_set_width(ui_City24, 150);
    lv_obj_set_height(ui_City24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City24, -50);
    lv_obj_set_y(ui_City24, -200);
    lv_obj_set_align(ui_City24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City24, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City24, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City24), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City25 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City25, "拉萨市\n日喀则市\n昌都市\n林芝市\n山南市\n那曲市");
    lv_obj_set_width(ui_City25, 150);
    lv_obj_set_height(ui_City25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City25, -50);
    lv_obj_set_y(ui_City25, -200);
    lv_obj_set_align(ui_City25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City25, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City25, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City25), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City26 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City26, "银川市\n石嘴山市\n吴忠市\n固原市\n中卫市");
    lv_obj_set_width(ui_City26, 150);
    lv_obj_set_height(ui_City26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City26, -50);
    lv_obj_set_y(ui_City26, -200);
    lv_obj_set_align(ui_City26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City26, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City26, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City26), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 163);
    lv_obj_set_y(ui_Button2, 184);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "查询");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -350);
    lv_obj_set_y(ui_Label5, -200);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "起始地:");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_Screen2);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 323);
    lv_obj_set_height(ui_Calendar1, 303);
    lv_obj_set_x(ui_Calendar1, -134);
    lv_obj_set_y(ui_Calendar1, 59);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -350);
    lv_obj_set_y(ui_Label1, -150);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "目的地:");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City27 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City27,
                            "乌鲁木齐市\n克拉玛依市\n吐鲁番市\n哈密市\n阿克苏地区\n喀什地区\n和田地区\n塔城地区\n阿勒泰地区\n昌吉回族自治州\n博尔塔拉蒙古自治州\n巴音郭楞蒙古自治州\n克孜勒苏柯尔克孜自治州\n伊犁哈萨克自治州\n石河子市\n阿拉尔市\n图木舒克市\n五家渠市\n北屯市\n铁门关市\n双河市\n可克达拉市\n昆玉市\n胡杨河市\n新星市\n白杨市");
    lv_obj_set_width(ui_City27, 150);
    lv_obj_set_height(ui_City27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City27, -50);
    lv_obj_set_y(ui_City27, -200);
    lv_obj_set_align(ui_City27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City27, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City27, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City27), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Province1 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_Province1,
                            "河北省\n山西省\n辽宁省\n吉林省\n黑龙江省\n江苏省\n浙江省\n安徽省\n福建省\n江西省\n山东省\n河南省\n湖北省\n湖南省\n广东省\n海南省\n四川省\n贵州省\n云南省\n陕西省\n甘肃省\n青海省\n台湾省\n内蒙古自治区\n广西壮族自治区\n西藏自治区\n宁夏回族自治区\n新疆维吾尔自治区\n其他");
    lv_obj_set_width(ui_Province1, 150);
    lv_obj_set_height(ui_Province1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Province1, -200);
    lv_obj_set_y(ui_Province1, -150);
    lv_obj_set_align(ui_Province1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Province1, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Province1, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Province1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Province1), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City29 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City29,
                            "石家庄市\n唐山市\n秦皇岛市\n邯郸市\n邢台市\n保定市\n张家口市\n承德市\n沧州市\n廊坊市\n衡水市");
    lv_obj_set_width(ui_City29, 150);
    lv_obj_set_height(ui_City29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City29, -50);
    lv_obj_set_y(ui_City29, -150);
    lv_obj_set_align(ui_City29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City29, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City29, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City29), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City30 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City30,
                            "太原市\n大同市\n阳泉市\n长治市\n晋城市\n朔州市\n晋中市\n运城市\n忻州市\n临汾市\n吕梁市\n");
    lv_obj_set_width(ui_City30, 150);
    lv_obj_set_height(ui_City30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City30, -50);
    lv_obj_set_y(ui_City30, -150);
    lv_obj_set_align(ui_City30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City30, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City30, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City30), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City31 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City31,
                            "沈阳市\n大连市\n鞍山市\n抚顺市\n本溪市\n丹东市\n锦州市\n营口市\n阜新市\n辽阳市\n盘锦市\n铁岭市\n朝阳市\n葫芦岛市");
    lv_obj_set_width(ui_City31, 150);
    lv_obj_set_height(ui_City31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City31, -50);
    lv_obj_set_y(ui_City31, -150);
    lv_obj_set_align(ui_City31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City31, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City31, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City31), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City32 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City32,
                            "长春市\n吉林市\n四平市\n辽源市\n通化市\n白山市\n松原市\n白城市\n延边朝鲜族自治州");
    lv_obj_set_width(ui_City32, 150);
    lv_obj_set_height(ui_City32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City32, -50);
    lv_obj_set_y(ui_City32, -150);
    lv_obj_set_align(ui_City32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City32, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City32, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City32), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City33 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City33,
                            "哈尔滨市\n齐齐哈尔市\n鸡西市\n鹤岗市\n双鸭山市\n大庆市\n伊春市\n佳木斯市\n七台河市\n牡丹江市\n黑河市\n绥化市\n大兴安岭地区");
    lv_obj_set_width(ui_City33, 150);
    lv_obj_set_height(ui_City33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City33, -50);
    lv_obj_set_y(ui_City33, -150);
    lv_obj_set_align(ui_City33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City33, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City33, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City33), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City34 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City34,
                            "南京市\n无锡市\n徐州市\n常州市\n苏州市\n南通市\n连云港市\n淮安市\n盐城市\n扬州市\n镇江市\n泰州市\n宿迁市");
    lv_obj_set_width(ui_City34, 150);
    lv_obj_set_height(ui_City34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City34, -50);
    lv_obj_set_y(ui_City34, -150);
    lv_obj_set_align(ui_City34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City34, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City34, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City34), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City35 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City35,
                            "杭州市\n宁波市\n温州市\n嘉兴市\n湖州市\n绍兴市\n金华市\n衢州市\n舟山市\n台州市\n丽水市");
    lv_obj_set_width(ui_City35, 150);
    lv_obj_set_height(ui_City35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City35, -50);
    lv_obj_set_y(ui_City35, -150);
    lv_obj_set_align(ui_City35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City35, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City35, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City35), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City36 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City36,
                            "合肥市\n芜湖市\n蚌埠市\n淮南市\n马鞍山市\n淮北市\n铜陵市\n安庆市\n黄山市\n滁州市\n阜阳市\n宿州市\n六安市\n亳州市\n池州市\n宣城市");
    lv_obj_set_width(ui_City36, 150);
    lv_obj_set_height(ui_City36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City36, -50);
    lv_obj_set_y(ui_City36, -150);
    lv_obj_set_align(ui_City36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City36, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City36, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City36), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City37 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City37,
                            "福州市\n厦门市\n莆田市\n三明市\n泉州市\n漳州市\n南平市\n龙岩市\n宁德市");
    lv_obj_set_width(ui_City37, 150);
    lv_obj_set_height(ui_City37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City37, -50);
    lv_obj_set_y(ui_City37, -150);
    lv_obj_set_align(ui_City37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City37, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City37, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City37), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City38 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City38,
                            "南昌市\n景德镇市\n萍乡市\n九江市\n新余市\n鹰潭市\n赣州市\n吉安市\n宜春市\n抚州市\n上饶市");
    lv_obj_set_width(ui_City38, 150);
    lv_obj_set_height(ui_City38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City38, -50);
    lv_obj_set_y(ui_City38, -150);
    lv_obj_set_align(ui_City38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City38, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City38, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City38), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City39 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City39,
                            "济南市\n青岛市\n淄博市\n枣庄市\n东营市\n烟台市\n潍坊市\n济宁市\n泰安市\n威海市\n日照市\n临沂市\n德州市\n聊城市\n滨州市\n菏泽市");
    lv_obj_set_width(ui_City39, 150);
    lv_obj_set_height(ui_City39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City39, -50);
    lv_obj_set_y(ui_City39, -150);
    lv_obj_set_align(ui_City39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City39, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City39, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City39), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City40 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City40,
                            "郑州市\n开封市\n洛阳市\n平顶山市\n安阳市\n鹤壁市\n新乡市\n焦作市\n濮阳市\n许昌市\n漯河市\n三门峡市\n南阳市\n商丘市\n信阳市\n周口市\n驻马店市\n济源市");
    lv_obj_set_width(ui_City40, 150);
    lv_obj_set_height(ui_City40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City40, -50);
    lv_obj_set_y(ui_City40, -150);
    lv_obj_set_align(ui_City40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City40, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City40, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City40, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City40), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City41 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City41,
                            "武汉市\n黄石市\n十堰市\n宜昌市\n襄阳市\n鄂州市\n荆门市\n孝感市\n荆州市\n黄冈市\n咸宁市\n随州市\n恩施土家族苗族自治州\n仙桃市\n潜江市\n天门市\n神农架林区");
    lv_obj_set_width(ui_City41, 150);
    lv_obj_set_height(ui_City41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City41, -50);
    lv_obj_set_y(ui_City41, -150);
    lv_obj_set_align(ui_City41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City41, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City41, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City41), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City42 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City42,
                            "长沙市\n株洲市\n湘潭市\n衡阳市\n邵阳市\n岳阳市\n常德市\n张家界市\n益阳市\n郴州市\n永州市\n怀化市\n娄底市\n湘西土家族苗族自治州");
    lv_obj_set_width(ui_City42, 150);
    lv_obj_set_height(ui_City42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City42, -50);
    lv_obj_set_y(ui_City42, -150);
    lv_obj_set_align(ui_City42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City42, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City42, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City42), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City43 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City43,
                            "广州市\n韶关市\n深圳市\n珠海市\n汕头市\n佛山市\n江门市\n湛江市\n茂名市\n肇庆市\n惠州市\n梅州市\n汕尾市\n河源市\n阳江市\n清远市\n东莞市\n中山市\n潮州市\n揭阳市\n云浮市");
    lv_obj_set_width(ui_City43, 150);
    lv_obj_set_height(ui_City43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City43, -50);
    lv_obj_set_y(ui_City43, -150);
    lv_obj_set_align(ui_City43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City43, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City43, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City43, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City43), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City44 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City44,
                            "海口市\n三亚市\n三沙市\n儋州市\n五指山市\n文昌市\n琼海市\n万宁市\n东方市");
    lv_obj_set_width(ui_City44, 150);
    lv_obj_set_height(ui_City44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City44, -50);
    lv_obj_set_y(ui_City44, -150);
    lv_obj_set_align(ui_City44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City44, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City44, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City44, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City44), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City45 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City45,
                            "成都市\n自贡市\n攀枝花市\n泸州市\n德阳市\n绵阳市\n广元市\n遂宁市\n内江市\n乐山市\n南充市\n宜宾市\n广安市\n达州市\n雅安市\n巴中市\n资阳市\n眉山市\n阿坝藏族羌族自治州\n甘孜藏族自治州\n凉山彝族自治州");
    lv_obj_set_width(ui_City45, 150);
    lv_obj_set_height(ui_City45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City45, -50);
    lv_obj_set_y(ui_City45, -150);
    lv_obj_set_align(ui_City45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City45, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City45, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City45, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City45), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City46 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City46,
                            "贵阳市\n六盘水市\n遵义市\n安顺市\n毕节市\n铜仁市\n黔西南布依族苗族自治州\n黔东南苗族侗族自治州\n黔南布依族苗族自治州");
    lv_obj_set_width(ui_City46, 150);
    lv_obj_set_height(ui_City46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City46, -50);
    lv_obj_set_y(ui_City46, -150);
    lv_obj_set_align(ui_City46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City46, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City46, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City46, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City46), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City47 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City47,
                            "昆明市\n曲靖市\n玉溪市\n保山市\n昭通市\n丽江市\n普洱市\n临沧市\n楚雄彝族自治州\n红河哈尼族彝族自治州\n文山壮族苗族自治州\n西双版纳傣族自治州\n大理白族自治州\n德宏傣族景颇族自治州\n怒江傈僳族自治州\n迪庆藏族自治州");
    lv_obj_set_width(ui_City47, 150);
    lv_obj_set_height(ui_City47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City47, -50);
    lv_obj_set_y(ui_City47, -150);
    lv_obj_set_align(ui_City47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City47, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City47, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City47, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City47), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City48 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City48,
                            "西安市\n铜川市\n宝鸡市\n咸阳市\n渭南市\n延安市\n汉中市\n榆林市\n安康市\n商洛市");
    lv_obj_set_width(ui_City48, 150);
    lv_obj_set_height(ui_City48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City48, -50);
    lv_obj_set_y(ui_City48, -150);
    lv_obj_set_align(ui_City48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City48, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City48, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City48, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City48), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City49 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City49,
                            "兰州市\n嘉峪关市\n金昌市\n白银市\n天水市\n武威市\n张掖市\n平凉市\n酒泉市\n庆阳市\n定西市\n陇南市\n临夏回族自治州\n甘南藏族自治州");
    lv_obj_set_width(ui_City49, 150);
    lv_obj_set_height(ui_City49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City49, -50);
    lv_obj_set_y(ui_City49, -150);
    lv_obj_set_align(ui_City49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City49, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City49, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City49, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City49), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City50 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City50,
                            "西宁市\n海东市\n海北藏族自治州\n黄南藏族自治州\n海南藏族自治州\n果洛藏族自治州\n玉树藏族自治州\n海西蒙古族藏族自治州");
    lv_obj_set_width(ui_City50, 150);
    lv_obj_set_height(ui_City50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City50, -50);
    lv_obj_set_y(ui_City50, -150);
    lv_obj_set_align(ui_City50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City50, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City50, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City50, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City50), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City51 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City51,
                            "台北市\n新北市\n桃园市\n台中市\n台南市\n高雄市\n基隆市\n新竹市\n嘉义市");
    lv_obj_set_width(ui_City51, 150);
    lv_obj_set_height(ui_City51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City51, -50);
    lv_obj_set_y(ui_City51, -150);
    lv_obj_set_align(ui_City51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City51, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City51, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City51, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City51), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City52 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City52,
                            "呼和浩特市\n包头市\n乌海市\n赤峰市\n通辽市\n鄂尔多斯市\n呼伦贝尔市\n巴彦淖尔市\n乌兰察布市");
    lv_obj_set_width(ui_City52, 150);
    lv_obj_set_height(ui_City52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City52, -50);
    lv_obj_set_y(ui_City52, -150);
    lv_obj_set_align(ui_City52, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City52, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City52, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City52, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City52), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City53 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City53,
                            "南宁市\n柳州市\n桂林市\n梧州市\n北海市\n防城港市\n钦州市\n贵港市\n玉林市\n百色市\n贺州市\n河池市\n来宾市\n崇左市");
    lv_obj_set_width(ui_City53, 150);
    lv_obj_set_height(ui_City53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City53, -50);
    lv_obj_set_y(ui_City53, -150);
    lv_obj_set_align(ui_City53, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City53, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City53, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City53, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City53), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City54 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City54, "拉萨市\n日喀则市\n昌都市\n林芝市\n山南市\n那曲市");
    lv_obj_set_width(ui_City54, 150);
    lv_obj_set_height(ui_City54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City54, -50);
    lv_obj_set_y(ui_City54, -150);
    lv_obj_set_align(ui_City54, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City54, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City54, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City54, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City54), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City55 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City55, "银川市\n石嘴山市\n吴忠市\n固原市\n中卫市");
    lv_obj_set_width(ui_City55, 150);
    lv_obj_set_height(ui_City55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City55, -50);
    lv_obj_set_y(ui_City55, -150);
    lv_obj_set_align(ui_City55, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City55, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City55, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City55, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City55), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City56 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City56,
                            "乌鲁木齐市\n克拉玛依市\n吐鲁番市\n哈密市\n阿克苏地区\n喀什地区\n和田地区\n塔城地区\n阿勒泰地区\n昌吉回族自治州\n博尔塔拉蒙古自治州\n巴音郭楞蒙古自治州\n克孜勒苏柯尔克孜自治州\n伊犁哈萨克自治州\n石河子市\n阿拉尔市\n图木舒克市\n五家渠市\n北屯市\n铁门关市\n双河市\n可克达拉市\n昆玉市\n胡杨河市\n新星市\n白杨市");
    lv_obj_set_width(ui_City56, 150);
    lv_obj_set_height(ui_City56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City56, -50);
    lv_obj_set_y(ui_City56, -150);
    lv_obj_set_align(ui_City56, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City56, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City56, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City56, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City56), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City57 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_City57, "北京市\n上海市\n天津市\n重庆市\n香港\n澳门");
    lv_obj_set_width(ui_City57, 150);
    lv_obj_set_height(ui_City57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City57, -50);
    lv_obj_set_y(ui_City57, -150);
    lv_obj_set_align(ui_City57, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_City57, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_City57, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_City57, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_City57), &ui_font_simfang,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 303);
    lv_obj_set_y(ui_Button3, 184);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "退出");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_simfang, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Province, ui_event_Province, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City, ui_event_City, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City1, ui_event_City1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City2, ui_event_City2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City3, ui_event_City3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City4, ui_event_City4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City5, ui_event_City5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City6, ui_event_City6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City7, ui_event_City7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City8, ui_event_City8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City9, ui_event_City9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City10, ui_event_City10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City11, ui_event_City11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City12, ui_event_City12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City13, ui_event_City13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City14, ui_event_City14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City15, ui_event_City15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City16, ui_event_City16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City17, ui_event_City17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City18, ui_event_City18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City19, ui_event_City19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City20, ui_event_City20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City21, ui_event_City21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City22, ui_event_City22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City28, ui_event_City28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City23, ui_event_City23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City24, ui_event_City24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City25, ui_event_City25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City26, ui_event_City26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Calendar1, ui_event_Calendar1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City27, ui_event_City27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Province1, ui_event_Province1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City29, ui_event_City29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City30, ui_event_City30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City31, ui_event_City31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City32, ui_event_City32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City33, ui_event_City33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City34, ui_event_City34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City35, ui_event_City35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City36, ui_event_City36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City37, ui_event_City37, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City38, ui_event_City38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City39, ui_event_City39, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City40, ui_event_City40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City41, ui_event_City41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City42, ui_event_City42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City43, ui_event_City43, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City44, ui_event_City44, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City45, ui_event_City45, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City46, ui_event_City46, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City47, ui_event_City47, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City48, ui_event_City48, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City49, ui_event_City49, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City50, ui_event_City50, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City51, ui_event_City51, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City52, ui_event_City52, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City53, ui_event_City53, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City54, ui_event_City54, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City55, ui_event_City55, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City56, ui_event_City56, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_City57, ui_event_City57, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
