// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Province(lv_event_t * e);
extern lv_obj_t * ui_Province;
void ui_event_City(lv_event_t * e);
extern lv_obj_t * ui_City;
void ui_event_City1(lv_event_t * e);
extern lv_obj_t * ui_City1;
void ui_event_City2(lv_event_t * e);
extern lv_obj_t * ui_City2;
void ui_event_City3(lv_event_t * e);
extern lv_obj_t * ui_City3;
void ui_event_City4(lv_event_t * e);
extern lv_obj_t * ui_City4;
void ui_event_City5(lv_event_t * e);
extern lv_obj_t * ui_City5;
void ui_event_City6(lv_event_t * e);
extern lv_obj_t * ui_City6;
void ui_event_City7(lv_event_t * e);
extern lv_obj_t * ui_City7;
void ui_event_City8(lv_event_t * e);
extern lv_obj_t * ui_City8;
void ui_event_City9(lv_event_t * e);
extern lv_obj_t * ui_City9;
void ui_event_City10(lv_event_t * e);
extern lv_obj_t * ui_City10;
void ui_event_City11(lv_event_t * e);
extern lv_obj_t * ui_City11;
void ui_event_City12(lv_event_t * e);
extern lv_obj_t * ui_City12;
void ui_event_City13(lv_event_t * e);
extern lv_obj_t * ui_City13;
void ui_event_City14(lv_event_t * e);
extern lv_obj_t * ui_City14;
void ui_event_City15(lv_event_t * e);
extern lv_obj_t * ui_City15;
void ui_event_City16(lv_event_t * e);
extern lv_obj_t * ui_City16;
void ui_event_City17(lv_event_t * e);
extern lv_obj_t * ui_City17;
void ui_event_City18(lv_event_t * e);
extern lv_obj_t * ui_City18;
void ui_event_City19(lv_event_t * e);
extern lv_obj_t * ui_City19;
void ui_event_City20(lv_event_t * e);
extern lv_obj_t * ui_City20;
void ui_event_City21(lv_event_t * e);
extern lv_obj_t * ui_City21;
void ui_event_City22(lv_event_t * e);
extern lv_obj_t * ui_City22;
void ui_event_City28(lv_event_t * e);
extern lv_obj_t * ui_City28;
void ui_event_City23(lv_event_t * e);
extern lv_obj_t * ui_City23;
void ui_event_City24(lv_event_t * e);
extern lv_obj_t * ui_City24;
void ui_event_City25(lv_event_t * e);
extern lv_obj_t * ui_City25;
void ui_event_City26(lv_event_t * e);
extern lv_obj_t * ui_City26;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
void ui_event_Calendar1(lv_event_t * e);
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_Label1;
void ui_event_City27(lv_event_t * e);
extern lv_obj_t * ui_City27;
void ui_event_Province1(lv_event_t * e);
extern lv_obj_t * ui_Province1;
void ui_event_City29(lv_event_t * e);
extern lv_obj_t * ui_City29;
void ui_event_City30(lv_event_t * e);
extern lv_obj_t * ui_City30;
void ui_event_City31(lv_event_t * e);
extern lv_obj_t * ui_City31;
void ui_event_City32(lv_event_t * e);
extern lv_obj_t * ui_City32;
void ui_event_City33(lv_event_t * e);
extern lv_obj_t * ui_City33;
void ui_event_City34(lv_event_t * e);
extern lv_obj_t * ui_City34;
void ui_event_City35(lv_event_t * e);
extern lv_obj_t * ui_City35;
void ui_event_City36(lv_event_t * e);
extern lv_obj_t * ui_City36;
void ui_event_City37(lv_event_t * e);
extern lv_obj_t * ui_City37;
void ui_event_City38(lv_event_t * e);
extern lv_obj_t * ui_City38;
void ui_event_City39(lv_event_t * e);
extern lv_obj_t * ui_City39;
void ui_event_City40(lv_event_t * e);
extern lv_obj_t * ui_City40;
void ui_event_City41(lv_event_t * e);
extern lv_obj_t * ui_City41;
void ui_event_City42(lv_event_t * e);
extern lv_obj_t * ui_City42;
void ui_event_City43(lv_event_t * e);
extern lv_obj_t * ui_City43;
void ui_event_City44(lv_event_t * e);
extern lv_obj_t * ui_City44;
void ui_event_City45(lv_event_t * e);
extern lv_obj_t * ui_City45;
void ui_event_City46(lv_event_t * e);
extern lv_obj_t * ui_City46;
void ui_event_City47(lv_event_t * e);
extern lv_obj_t * ui_City47;
void ui_event_City48(lv_event_t * e);
extern lv_obj_t * ui_City48;
void ui_event_City49(lv_event_t * e);
extern lv_obj_t * ui_City49;
void ui_event_City50(lv_event_t * e);
extern lv_obj_t * ui_City50;
void ui_event_City51(lv_event_t * e);
extern lv_obj_t * ui_City51;
void ui_event_City52(lv_event_t * e);
extern lv_obj_t * ui_City52;
void ui_event_City53(lv_event_t * e);
extern lv_obj_t * ui_City53;
void ui_event_City54(lv_event_t * e);
extern lv_obj_t * ui_City54;
void ui_event_City55(lv_event_t * e);
extern lv_obj_t * ui_City55;
void ui_event_City56(lv_event_t * e);
extern lv_obj_t * ui_City56;
void ui_event_City57(lv_event_t * e);
extern lv_obj_t * ui_City57;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TextArea2;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label10;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_interface2_png);    // assets/Interface2.png



LV_FONT_DECLARE(ui_font_simfang);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
