// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include "ui_events.h"
#include "../Inc/HTTP.h"
#include "../Inc/List.h"
#include <pthread.h>

extern Node * head;

char add[30];	// 用于存储起始城市的字符串
char end[30];	// 用于存储目的地的字符串

/////////////////////////////////

lv_obj_t * ui_CITY_Local[29] = {0};
lv_obj_t * ui_CITY_Destination[29] = {0};
lv_calendar_date_t date[1] = {0};

void Choose_Provinces(uint16_t Province_selected)
{
	// Your code here
	ui_CITY_Local[0] = ui_City;
	ui_CITY_Local[1] = ui_City1;
	ui_CITY_Local[2] = ui_City2;
	ui_CITY_Local[3] = ui_City3;
	ui_CITY_Local[4] = ui_City4;
	ui_CITY_Local[5] = ui_City5;
	ui_CITY_Local[6] = ui_City6;
	ui_CITY_Local[7] = ui_City7;
	ui_CITY_Local[8] = ui_City8;
	ui_CITY_Local[9] = ui_City9;
	ui_CITY_Local[10] = ui_City10;
	ui_CITY_Local[11] = ui_City11;
	ui_CITY_Local[12] = ui_City12;
	ui_CITY_Local[13] = ui_City13;
	ui_CITY_Local[14] = ui_City14;
	ui_CITY_Local[15] = ui_City15;
	ui_CITY_Local[16] = ui_City16;
	ui_CITY_Local[17] = ui_City17;
	ui_CITY_Local[18] = ui_City18;
	ui_CITY_Local[19] = ui_City19;
	ui_CITY_Local[20] = ui_City20;
	ui_CITY_Local[21] = ui_City21;
	ui_CITY_Local[22] = ui_City22;
	ui_CITY_Local[23] = ui_City23;
	ui_CITY_Local[24] = ui_City24;
	ui_CITY_Local[25] = ui_City25;
	ui_CITY_Local[26] = ui_City26;
	ui_CITY_Local[27] = ui_City27;
	ui_CITY_Local[28] = ui_City28;

	char province_local[128] = {0};	// 用于存储所选省份的字符串

	for (int j = 0; j < 29; j++)
	if (Province_selected == j)
	{
	    lv_obj_add_flag(ui_CITY_Local[j], LV_OBJ_FLAG_CLICKABLE);	// 所选设置为可点击
	    lv_obj_clear_flag(ui_CITY_Local[j], LV_OBJ_FLAG_HIDDEN);	// 所选设置为可见

		lv_dropdown_get_selected_str(ui_Province, province_local, sizeof(province_local));	// 获取所选省份的字符串的字符串
		printf("当前离开的省份是：%s\n", province_local);	// 打印所选省份

		char citylocal[50] = {0};		// 用于存储所选城市的字符串
		memset(add, 0, sizeof(add));	// 初始化数组
		lv_dropdown_get_selected_str(ui_CITY_Local[j], citylocal, sizeof(citylocal));	// 初始化城市
		strcpy(add, citylocal);	// 将所选城市字符串复制到输出缓冲区
		printf("即将离开的城市是：%s\n", add);	// 打印所选城市
		add[strlen(citylocal) - 3] = '\0';	// 删除最后一个字符
	}
	else
	{
	    lv_obj_add_flag(ui_CITY_Local[j], LV_OBJ_FLAG_HIDDEN);		// 未选设置为隐藏
	    lv_obj_clear_flag(ui_CITY_Local[j], LV_OBJ_FLAG_CLICKABLE);	// 未选设置为不可点击
	}

}

void Province_Change(lv_event_t * e)
{
	// Your code here
    uint16_t Province_selected = lv_dropdown_get_selected(ui_Province); 	// 获取当前选中的索引
    Choose_Provinces(Province_selected);
}


void Choose_Provinces1(uint16_t Province_selected)
{
	// Your code here
	ui_CITY_Destination[0] = ui_City29;
	ui_CITY_Destination[1] = ui_City30;
	ui_CITY_Destination[2] = ui_City31;
	ui_CITY_Destination[3] = ui_City32;
	ui_CITY_Destination[4] = ui_City33;
	ui_CITY_Destination[5] = ui_City34;
	ui_CITY_Destination[6] = ui_City35;
	ui_CITY_Destination[7] = ui_City36;
	ui_CITY_Destination[8] = ui_City37;
	ui_CITY_Destination[9] = ui_City38;
	ui_CITY_Destination[10] = ui_City39;
	ui_CITY_Destination[11] = ui_City40;
	ui_CITY_Destination[12] = ui_City41;
	ui_CITY_Destination[13] = ui_City42;
	ui_CITY_Destination[14] = ui_City43;
	ui_CITY_Destination[15] = ui_City44;
	ui_CITY_Destination[16] = ui_City45;
	ui_CITY_Destination[17] = ui_City46;
	ui_CITY_Destination[18] = ui_City47;
	ui_CITY_Destination[19] = ui_City48;
	ui_CITY_Destination[20] = ui_City49;
	ui_CITY_Destination[21] = ui_City50;
	ui_CITY_Destination[22] = ui_City51;
	ui_CITY_Destination[23] = ui_City52;
	ui_CITY_Destination[24] = ui_City53;
	ui_CITY_Destination[25] = ui_City54;
	ui_CITY_Destination[26] = ui_City55;
	ui_CITY_Destination[27] = ui_City56;
	ui_CITY_Destination[28] = ui_City57;

	char province_destination[128] = {0};	// 用于存储所选省份的字符串

	for (int j = 0; j < 29; j++)
	if (Province_selected == j)
	{


	    lv_obj_add_flag(ui_CITY_Destination[j], LV_OBJ_FLAG_CLICKABLE);
	    lv_obj_clear_flag(ui_CITY_Destination[j], LV_OBJ_FLAG_HIDDEN);

		lv_dropdown_get_selected_str(ui_Province1, province_destination, sizeof(province_destination));	// 获取所选省份的字符串的字符串
		printf("即将到达的省份是：%s\n", province_destination);	// 打印所选省份

		char citylocal[50] = {0};		// 用于存储所选城市的字符串
		memset(end, 0, sizeof(end));	// 初始化数组
		lv_dropdown_get_selected_str(ui_CITY_Destination[j], citylocal, sizeof(citylocal));	// 初始化城市
		strcpy(end, citylocal);	// 将所选城市字符串复制到输出缓冲区
		printf("即将到达的城市是：%s\n", end);	// 打印所选城市		
		end[strlen(citylocal) - 3] = '\0';	// 删除最后一个字符
	}
	else
	{
	    lv_obj_add_flag(ui_CITY_Destination[j], LV_OBJ_FLAG_HIDDEN);
	    lv_obj_clear_flag(ui_CITY_Destination[j], LV_OBJ_FLAG_CLICKABLE);
	}
}
void Province_Change1(lv_event_t * e)
{
	// Your code here
    uint16_t Province_selected = lv_dropdown_get_selected(ui_Province1); 	// 获取当前选中的索引
    Choose_Provinces1(Province_selected);
}

void City_Change(lv_event_t * e)
{
	// Your code here
	lv_obj_t * target = lv_event_get_target(e);
	char citylocal[50] = {0};		// 用于存储所选城市的字符串
	memset(add, 0, sizeof(add));	// 初始化数组
	lv_dropdown_get_selected_str(target, citylocal, sizeof(citylocal));	// 获取所选城市的字符串
	//printf("%d\n", strlen(citylocal));	// 打印字符串的大小
	//citylocal[sizeof(Province_selected) - 2] = '\0';	// 确保字符串以空字符结尾
	printf("当前选择的城市是：%s\n", citylocal);	// 打印所选城市
	strcpy(add, citylocal);	// 将所选城市字符串复制到输出缓冲区
	add[strlen(citylocal) - 3] = '\0';	// 删除最后一个字符
	printf("当前存储的城市是：%s\n", add);	// 打印存储的城市
}

void City_Change1(lv_event_t * e)
{
	// Your code here
	lv_obj_t * target = lv_event_get_target(e);
	char citylocal[50] = {0};	// 用于存储所选城市的字符串
	memset(end, 0, sizeof(end));	// 初始化数组
	lv_dropdown_get_selected_str(target, citylocal, sizeof(citylocal));	// 获取所选城市的字符串
	//printf("%d\n", strlen(citylocal));	// 打印字符串的大小
	//citylocal[sizeof(Province_selected) - 2] = '\0';	// 确保字符串以空字符结尾
	printf("当前选择的城市是：%s\n", citylocal);	// 打印所选城市
	strcpy(end, citylocal);	// 将所选城市字符串复制到输出缓冲区
	end[strlen(citylocal) - 3] = '\0';	// 删除最后一个字符
	printf("当前存储的城市是：%s\n", end);	// 打印存储的城市
}
void Time_Get(lv_event_t * e)
{
	// Your code here
	lv_calendar_get_pressed_date(ui_Calendar1, date);				// 获取日历控件中被按下的日期
	lv_calendar_set_highlighted_dates(ui_Calendar1, date, 1);		// 调用函数，将选中的日期设为高亮
	printf("%d-%02d-%02d\n", date->year, date->month, date->day);
}

void Time_Init()
{
	time_t timep;
	struct tm *p;
	char time_str[28];

	time(&timep); // 获取当前时间的秒数
	p = gmtime(&timep); // 将秒数转换为 tm 结构体

	lv_calendar_set_today_date(ui_Calendar1, p->tm_year + 1900, p->tm_mon + 1, p->tm_mday);		// 设置日历控件中的当前日期
	lv_calendar_set_showed_date(ui_Calendar1, p->tm_year + 1900, p->tm_mon + 1);				// 设置日历控件中显示的日期

	date->year = p->tm_year + 1900;
	date->month = p->tm_mon + 1;
	date->day = p->tm_mday;

	printf("当前时间：%d-%02d-%02d\n", date->year, date->month, date->day);
}

void Datas_Putout(lv_event_t * e)
{
	head = Head_Init();
	pthread_t tid; 

	lv_textarea_set_text(ui_TextArea2, "");
    lv_textarea_set_placeholder_text(ui_TextArea2, "加载中...\n");
	lv_refr_now(NULL);

	pthread_create(&tid, NULL, Get_Datas, NULL);
	sleep(10);
	lv_textarea_set_text(ui_TextArea2, "");
	if(head->next == NULL || head->code == 400)
	{
		lv_textarea_add_text(ui_TextArea2, "无结果\n");
	}
	else
	{
		Node * temp = head->next;
		char buffer[512] = ""; 
		// int offset = 0;

		while(temp != NULL)
		{
			sprintf(buffer, "%s\t\t%s\t%s\t\t%s\t%s\t\t%s\t%s\t%s\n", 
				temp->train_number, temp->depart_city, temp->depart_name, temp->arrive_city, temp->arrive_name, 
				temp->depart_time, temp->arrive_time, temp->date);

			lv_textarea_add_text(ui_TextArea2, buffer);
			
			temp = temp->next;
		}
	}
} 


void Re_Fresh(lv_event_t * e)
{
	// Your code here
	lv_textarea_set_text(ui_TextArea2, "");
    lv_textarea_set_placeholder_text(ui_TextArea2, "加载中...\n");
	//ui_Screen3_screen_init();
	printf("刷新加载中...\n");

	// pthread_t tid;
	// pthread_create(&tid, NULL, Datas_Putout, NULL);

	Datas_Putout(e);

}



