// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

//声明全局变量
extern char add[30];	
extern char end[30];	

extern lv_obj_t * ui_CITY_Local[29];
extern lv_obj_t * ui_CITY_Destination[29];
extern lv_calendar_date_t date[1];


void City_Change(lv_event_t * e);
void City_Change1(lv_event_t * e);

void Choose_Provinces(uint16_t Province_selected);
void Choose_Provinces1(uint16_t Province_selected);

void Province_Change(lv_event_t * e);
void Province_Change1(lv_event_t * e);

void Time_Get(lv_event_t * e);
void Time_Init();

void Re_Fresh(lv_event_t * e);
void Datas_Putout(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif